vich_uploader:
    db_driver: orm

    mappings:
        user_avatar:
            uri_prefix: /images/user_avatar
            upload_destination: "%kernel.project_dir%/public/images/user_avatar"
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
